Final content for the first blog
timberio/content pull request #3
Opened 2018-05-23 04:53 UTC by hackintoshrao

- Blog on getting started with Apache Kafka.
- The first part deals with conveying the need for a system like Kafka and how does it fit along with rest of the pieces in the backend.
- Second part deals with using installing and using Apache Kafka.

2018-05-23 13:27 UTC, zsherman commented
thanks @hackintoshrao! I'm going to have @sidhanthp take a look through and make any comments as necessary 👍

2018-05-23 16:28 UTC, sidhanthp requested changes
Thanks for the great writeup! Made some grammar changes (already committed to master) and left some feedback for some things to add. If you could redo the charts in LucidChart so they're ready to be uploaded to the site, I'd really appreciate that.

2018-05-23 16:28 UTC, sidhanthp commented on posts/hello-world-in-kafka-using-python.md
> +3. What if you have data processing systems in place to process these events to gain deeper insights? Since these systems wouldn't be capable of handling high frequency reads and you wouldn't have ac
What do you mean when you say "you wouldn't have access to the _true source of data_"? I see you wrote below that we have 'all the different systems residing in one single place', can't you still have a single source of data by joining together sql tables?

2018-05-23 16:28 UTC, sidhanthp commented on posts/hello-world-in-kafka-using-python.md
> +1. Store huge amount of data that can be persistent, checksummed and replicated for fault tolerance
Explain why we want our data to be 'persistent, checksummed, and replicated'

2018-05-23 16:28 UTC, sidhanthp commented on posts/hello-world-in-kafka-using-python.md
> +Kafka makes use something called as ZooKeeper which is a centralized service for a distributed environment like Kafka. It offers configuration service, synchronisation service and naming registry for
Why is ZooKeeper necessary and what does it do in layman terms? Don't just link them to the documentation.

2018-05-23 16:28 UTC, sidhanthp commented on posts/hello-world-in-kafka-using-python.md
> +Let us start by creating a `sample` kafka topic with a single partition and replica. This can be done using the following command:
Explain what it means to have a _single partition and replica_?

2018-05-23 16:28 UTC, sidhanthp commented on posts/hello-world-in-kafka-using-python.md
> +Thus, a simple `Hello, World! in Kafka using Python`.
Are there any drawbacks that can come from using Kafka? What are they?

2018-05-23 16:28 UTC, sidhanthp commented on posts/hello-world-in-kafka-using-python.md
> +![Simple Architecture](../images/kafka-image-three.jpg)
I think putting arrows in both directions from all the items would show that any of the items can be a producer/consumer

2018-05-23 16:28 UTC, sidhanthp commented on posts/hello-world-in-kafka-using-python.md
> +1. Store huge amount of data that can be persistent, checksummed and replicated for fault tolerance
Explain why we want our data to be _persistent, checksummed, and replicated_

2018-05-23 16:28 UTC, sidhanthp commented on posts/hello-world-in-kafka-using-python.md
> +3. What if you have data processing systems in place to process these events to gain deeper insights? Since these systems wouldn't be capable of handling high frequency reads and you wouldn't have ac
Explain what it means to be a _true source of data_? I saw later in the post you wrote that we 'have all the data from all different systems residing at a single place making Kafka a true source of data', but why can't SQL DB's that link to each other also be a true source of data?

2018-05-25 13:08 UTC, zsherman commented
@sidhanthp can you handle the charts? 

@hackintoshrao @abraarsyed I think we're almost ready, could we just address some of Sid's comments?

2018-05-25 15:34 UTC, abraarsyed commented
@zsherman Hey there, you are right! We will look into the suggested changes and make the necessary changes as soon as possible :D

2018-05-25 15:38 UTC, sidhanthp commented
@abraarsyed Thank you! The charts are finished, just make the changes and submit when you can. Looks like the article is almost done, good job guys!

2018-05-25 20:13 UTC, merged

2018-05-25 20:16 UTC, sidhanthp commented
Hey guys, I ended up just making the changes and merging it in. Thank you for helping us with the writeup, it was very well done! You should see it posted on Tuesday morning. We'll give you all the credit in the article and put your twitter handle when we blast it out.

2018-05-26 04:58 UTC, hackintoshrao commented
Thank you @sidhanthp . We are working on couple more blogs.